### PR TITLE
Fix galambox

### PR DESCRIPTION
**Pull request by lrnv**
Should supplant #219 if @Santymax98 you agree ?

### CODE REVIEW

**Comment by Santymax98** [comment]
I just checked, it's perfect... I had tried it quite a bit. I'm a little busy... I think this is good. We should look for which values ​​of the parameters give numerical problems, for example for galambos it was approximately "19.6"... it would be interesting to see if the same thing happens with other types of copulas and determine in which parameters the generation of samples begins to fail to repair it. So far I can't find it but it would be interesting.

**Comment by lrnv** [comment]
Maybe you could add here a test on the problematic parametrisation for galambos ?

**Comment by Santymax98** [comment]
Are you referring to examples where the parameter is greater than 19.6? With this solution that we implemented we are getting good samples... for large parameters in fact for parameters greater than "75" which I believe is the maximum limit in the `copula` package of `R`.

**Comment by lrnv** [comment]
Yes exactly, maybe we should write that down in the tests ? So that if, someday, we modify the algorithm and the samples are not as good, we'll know about it imediately

**Comment by Santymax98** [comment]
understood. I'm going to do it...

**Comment by lrnv** [comment]
Sorry I did not remember that you added an example in #219 ! I just added a test correpsonding to your example, is that enough in your oppinon ?

**Comment by Santymax98** [comment]
yes... I was doing this...
```julia
@testitem "small extreme sampling test" begin
    using Copulas, Distributions, HypothesisTests
    
    params = [20, 60, 70, 80, 120, 210]
    for θ in params 
        cop = GalambosCopula(θ)
        data = rand(cop, 10^4)
        
        # Check data size
        @test size(data) == (2, 100)
    end
    @test true
end
```

**Comment by lrnv** [comment]
I simply refactored the test files because they were very verbose. I'll wait for the online CI to go green and then I'll merge this. TY Santiago :)

**Comment by Santymax98** [comment]
ok, it's perfect for me

**Pull request merged**
