### PR TITLE
Remove overflows for bivariate gumbel density

### LINKED ISSUE #215: [FR] : implementing derivatives for the Gumbel Generator
Hi dear Oskar. 

Do you know why these errors of this type occur?

```julia
julia> G = GumbelCopula(2, 244.3966206319112)
GumbelCopula{2, Float64}(
G: Copulas.GumbelGenerator{Float64}(244.3966206319112)
)


julia> u = [0.969034207932297,0.9638122014293545]
2-element Vector{Float64}:
 0.969034207932297
 0.9638122014293545

julia> pdf(G, u)
ERROR: DomainError with  1.0 t + 𝒪(t³) :
The 0-th order Taylor1 coefficient must be non-zero
to raise the Taylor1 polynomial to a non-integer exponent.
Stacktrace:
  [1] pow!
    @ C:\Users\Pastor Jose Andres J\.julia\packages\TaylorSeries\wwiDC\src\power.jl:208 [inlined]
  [2] ^(a::TaylorSeries.Taylor1{Float64}, r::Float64)
    @ TaylorSeries C:\Users\Pastor Jose Andres J\.julia\packages\TaylorSeries\wwiDC\src\power.jl:111
  [3] ϕ(G::Copulas.GumbelGenerator{Float64}, t::TaylorSeries.Taylor1{Float64})
    @ Copulas C:\Users\Pastor Jose Andres J\.julia\packages\Copulas\SPHR4\src\Generator\UnivariateGenerator\GumbelGenerator.jl:40
  [4] ϕ⁽ᵏ⁾(G::Copulas.GumbelGenerator{Float64}, k::Int64, t::Float64)
    @ Copulas C:\Users\Pastor Jose Andres J\.julia\packages\Copulas\SPHR4\src\Generator.jl:40
  [5] ϕ⁽ᵏ⁾
    @ C:\Users\Pastor Jose Andres J\.julia\packages\Copulas\SPHR4\src\ArchimedeanCopula.jl:54 [inlined]
  [6] _logpdf(C::GumbelCopula{2, Float64}, u::Vector{Float64})
    @ Copulas C:\Users\Pastor Jose Andres J\.julia\packages\Copulas\SPHR4\src\ArchimedeanCopula.jl:76
  [7] logpdf
    @ C:\Users\Pastor Jose Andres J\.julia\packages\Distributions\ji8PW\src\common.jl:263 [inlined]
  [8] _pdf
    @ C:\Users\Pastor Jose Andres J\.julia\packages\Distributions\ji8PW\src\common.jl:237 [inlined]
  [9] pdf(d::GumbelCopula{2, Float64}, x::Vector{Float64})
    @ Distributions C:\Users\Pastor Jose Andres J\.julia\packages\Distributions\ji8PW\src\common.jl:222
 [10] top-level scope
    @ REPL[3]:1
```

### PR DESCRIPTION
**Pull request by lrnv**
Fixes #215

@Santymax98 please tell me what you think about this. Basically I rewrote the bivariate gumbel density to leverage the `logaddexp` function that compute without mistake `log(exp(a)+exp(b))`, whic is in the code of thebivariate gumbel density. 

I guess that the same thing could be done for multivariate cases.. @Santymax98 Do you by chance know a reference where the formula for the multivariate gumbel density is written ? 

PS: I am not sure the values yielded are the right one... It looks like i have made a mistake while deriving it...

### CODE REVIEW

**Comment by lrnv** [comment]
Yes I think this approach is bounded to bivariate cases. Maybe you could add a test that check it up against your bivariate version on "normal" parameters to be sure that we have the same outputs ?

**Comment by Santymax98** [comment]
I finished doing my tests... the way you present gives me this error
```Julia
ERROR: DomainError with 1.0 t + 𝒪(t³) :
The 0-th order Taylor1 coefficient must be non-zero
to raise the Taylor1 polynomial to a non-integer exponent.
Stacktrace:
  [1] pow!
    @ C:\Users\Pastor Jose Andres J\.julia\packages\TaylorSeries\wwiDC\src\power.jl:208 [inlined]
  [2] ^(a::TaylorSeries.Taylor1{Float64}, r::Float64)
    @ TaylorSeries C:\Users\Pastor Jose Andres J\.julia\packages\TaylorSeries\wwiDC\src\power.jl:111
  [3] ϕ(G::Copulas.GumbelGenerator{Float64}, t::TaylorSeries.Taylor1{Float64})
    @ Copulas C:\Users\Pastor Jose Andres J\.julia\dev\Copulas.jl\src\Generator\UnivariateGenerator\GumbelGenerator.jl:40
  [4] ϕ⁽ᵏ⁾(G::Copulas.GumbelGenerator{Float64}, k::Int64, t::Float64)
    @ Copulas C:\Users\Pastor Jose Andres J\.julia\dev\Copulas.jl\src\Generator.jl:40
  [5] ϕ⁽ᵏ⁾
    @ C:\Users\Pastor Jose Andres J\.julia\dev\Copulas.jl\src\ArchimedeanCopula.jl:54 [inlined]
  [6] _logpdf(C::GumbelCopula{2, Float64}, u::Vector{Float64})
    @ Copulas C:\Users\Pastor Jose Andres J\.julia\dev\Copulas.jl\src\ArchimedeanCopula.jl:76
  [7] logpdf
    @ C:\Users\Pastor Jose Andres J\.julia\packages\Distributions\ji8PW\src\common.jl:263 [inlined]
  [8] _pdf
    @ C:\Users\Pastor Jose Andres J\.julia\packages\Distributions\ji8PW\src\common.jl:237 [inlined]
  [9] pdf(d::GumbelCopula{2, Float64}, x::Vector{Float64})
    @ Distributions C:\Users\Pastor Jose Andres J\.julia\packages\Distributions\ji8PW\src\common.jl:222
 [10] top-level scope
    @REPL[5]:1
```

**Comment by lrnv** [comment]
This is weird as i do not have that in here. Wht test are you running ?

**Comment by lrnv** [comment]
@Santymax98 I think I nailed it this time :)

**Comment by lrnv** [comment]
SInce there are tests w.r.t. to the logcopula, i think this can be merged.

**Pull request merged**
