### PR TITLE
fix typo in formula

### PR DESCRIPTION
**Pull request by szcf-weiya**
the backtick is redundant
image

also fix some typo in the docstring

### CODE REVIEW

**Comment by lrnv** [comment]
Thanks again ! I'll keep this one open for a bit in case you find other ones so tha tyou dont have to make new branches again.

**Comment by szcf-weiya** [comment]
image
fixed in https://github.com/lrnv/Copulas.jl/pull/102/commits/b387d6a76e8a45c2e5ba81a2c081bc1e9d13d51e

**Comment by lrnv** [comment]
How are you liking the documentation btw ? Do not hesitate if you think some part is unclear (also, consider reading the dev version since it has received a few fixes since the stable one)

**Comment by szcf-weiya** [comment]
I think the documentation is well-organized! Thanks.

**Comment by lrnv** [comment]
I'll merge then ! Thanks a lot, do not hesitate if you have any questions :)

**Pull request merged**
