### PR TITLE
[Bug] RafteryCopula fixes.

### LINKED ISSUE #98: [RafteryCopula] broken tests
@Santymax98 There are broken tests in Rafterycopula, as when we merged your PR we forgot to run them...

[On the pdf here](https://github.com/lrnv/Copulas.jl/blob/c9046d22ccdffdf5649cdb756d10abf7a0811128/test/RafteryTest.jl#L25-L26)

[On the cdf there](https://github.com/lrnv/Copulas.jl/blob/c9046d22ccdffdf5649cdb756d10abf7a0811128/test/RafteryTest.jl#L49)

This is problematic, I had the pdf retuninrg negative values on some test cases. Would you mind checking again the coirrectness of your code ? 

Cheers

### PR DESCRIPTION
**Pull request by lrnv**
Fixes #98

@Santymax98 it loks like the pdf is now fixed, but the cdf has values that still do not match what is in the tests files (see the @test_broken).

two month ago there https://github.com/lrnv/Copulas.jl/issues/98#issuecomment-1839262280 you proposed to use 

```julia
function prueba(R::Vector{T}, u::Vector{T}) where T
    # Order the vector u
    u_ordered = sort(u)
    println("Sorted vector: ", u_ordered)
    
    term1 = u_ordered[1]
    println("Term 1: ", term1)
    
    term2 = ((1 - R[1]) * (1 - R[2])) / (1 - R[1] - R[2]) * prod(u)^(1/(1 - R[1]))
    println("Term 2: ", term2)
    
    term3 = 0.0
    for i in 2:length(R) # <<<<<<<<--------------- This should be 2:d and not 2:length(R) since length(R) is not the dimension. 
        prod_prev = prod(u_ordered[1:i-1])
        term3_part = (R[1] * (1 - R[1])) / ((1 - R[1] - i) * (2 - R[1] - i)) * prod_prev^(1/(1 - R[1])) * u_ordered[i]^((2 - R[1] - i) / (1 - R[1]))
        println("Term 3 (part $i): ", term3_part)
        term3 += term3_part
    end
    
    # Combine the terms to get the cumulative distribution function
    cdf_value = term1 + term2 - term3
    println("Final CDF value: ", cdf_value)
    
    return cdf_value
end

prueba([0.5,3], [0.1,0.2,0.3])
```

to check that the value's returned by the code are indeed correct. But your code has a mistake. 

It looks to me like the current implementation is mathcing what is in the article, so maybe the issue is that the tests values are now wrong and should be updated ?

### CODE REVIEW

**Comment by Santymax98** [comment]
I'm going to read it, in the morning I'm working but later I'll be free and
I hope to review the tests.


I remember that I did the tests with paper and pencil according to the
formula in the document.

**Comment by Santymax98** [comment]
```julia
function prueba_CDF(R::Vector{T}, u::Vector{T}) where T
    # Order the vector u
    θ = R[1]
    println("param:", θ)
    d = round(Int, R[2])
    println("dimension:", d)
    u_ordered = sort(u)
    println("Sorted vector: ", u_ordered)
    
    term1 = u_ordered[1]
    println("Term 1: ", term1)
    
    term2 = ((1 - θ) * (1 -d)) / (1 - θ - d) * prod(u)^(1/(1 - θ))
    println("Term 2: ", term2)
    
    term3 = 0.0
    for i in 2:d # <<<<<<<<--------------- This should be 2:d and not 2:length(R) since length(R) is not the dimension. 
        prod_prev = prod(u_ordered[1:i-1])
        term3_part = ((θ * (1 - θ)) / ((1 - θ - i) * (2 - θ - i))) * prod_prev^(1/(1 - θ)) * u_ordered[i]^((2 - θ - i) / (1 - θ))
        println("Term 3 (part $i): ", term3_part)
        term3 += term3_part
    end
    
    # Combine the terms to get the cumulative distribution function
    cdf_value = term1 + term2 - term3
    println("Final CDF value: ", cdf_value)
    
    return cdf_value
end

prueba_CDF([0.5,3], [0.1,0.2,0.3])
```

should be 0.08236... I calculated this value manually and the test code works fine. However, when I combine it with Copulas.jl it gives me the error that we have had so far.

**Comment by Santymax98** [comment]
```julia
function prueba_PDF(R::Vector{T}, u::Vector{T}) where T
    # Order the vector u
    θ = R[1]
    d = round(Int, R[2])
    u_ordered = sort(u)
    println("Sorted vector: ", u_ordered)
    
    term1 = (1/(((1-θ)^(d-1))*(1-θ-d)))
    println("Term 1: ", term1)
    
    term2 = (1-d-θ*(u_ordered[d])^((1-θ-d)/(1-θ)))
    println("Term 2: ", term2)
    
    term3 = (prod(u))^((θ)/(1-θ))
    println(term3)
    # Combine the terms to get the density distribution function
    pdf_value = term1*term2*term3
    println("Final PDF value: ", pdf_value)
    
    return pdf_value
end
prueba_PDF([0.5,3], [0.1,0.2,0.3])
```

Regarding this test, the value in this case should be 1.99450... and on my machine the results are coming out correct.

**Comment by lrnv** [comment]
@Santymax98 I cleared up the code and fixed the previous value. I included your versions as fallbak testing. Thanks a lot this is now Ok for me !

**Pull request merged**
